name: zk-kit.solidity
description: A monorepo of reusable contracts for zero-knowledge technologies.
license: MIT
repository: git@github.com:privacy-scaling-explorations/zk-kit.solidity.git
homepage: https://github.com/privacy-scaling-explorations/zk-kit.solidity
bugs: https://github.com/privacy-scaling-explorations/zk-kit.solidity/issues
private: true
scripts:
    compile: yarn workspaces foreach -Ap run compile
    test: yarn workspaces foreach -Ap run test:coverage
    version:bump: |
        yarn workspace @zk-kit/${0}.sol version ${1} &&
        yarn remove:stable-version-field ${0} &&
        NO_HOOK=1 git commit -am "chore(${0}): v${1}" &&
        git tag ${0}.sol-v${1}
    version:publish: yarn workspaces foreach -A --no-private npm publish --tolerate-republish --access public
    version:release: changelogithub
    format: prettier -c .
    format:write: prettier -w .
    remove:stable-version-field: scripts/remove-stable-version-field.ts ${0} && yarn format:write
    postinstall: husky && git config --local core.editor cat
keywords: [solidity, monorepo, zero-knowledge, zk-snarks]
packageManager: pnpm@9.4.0
devDependencies:
    "@commitlint/cli": ^18.6.1
    "@commitlint/config-conventional": ^18.6.2
    "@types/glob": ^7.2.0
    "@types/node": ^20
    changelogithub: ^0.13.3
    czg: ^1.9.1
    husky: ^9.0.11
    lint-staged: ^15.2.2
    prettier: ^3.2.5
    ts-node: ^10.9.2
    typescript: ^5.3.3
pnpm:
    patchedDependencies:
        changelogithub@0.13.3: patches/changelogithub@0.13.3.patch
